export const USER_PROFILE_DETAILS_REQUEST = 'USER_PROFILE_DETAILS_REQUEST';
export const USER_PROFILE_DETAILS_SUCCESS = 'USER_PROFILE_DETAILS_SUCCESS';
export const USER_PROFILE_DETAILS_FAIL = 'USER_PROFILE_DETAILS_FAIL';
export const USER_PROFILE_DETAILS_RESET = 'USER_PROFILE_DETAILS_RESET';
